import { cp, readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	createProject,
	forgeEnvironment,
	pathExists,
	readJson,
	repoRoot,
	runCommand,
	runForge,
	withScenarioWorkspace,
	writeJson,
} from "../utils/harness";
import { installPackedForge, packPackage } from "../utils/packed";

const effectVersion: string = createRequire(import.meta.url)(
	"effect/package.json",
).version;

const registryId = "@example/forge-registry";

interface RegistryPackageJson {
	readonly dependencies: Readonly<Record<string, string>>;
	readonly name: string;
	readonly version: string;
}

interface RegistryManifest {
	readonly installs: ReadonlyArray<{
		readonly definitionId: string;
		readonly targets: ReadonlyArray<{
			readonly kind: "module" | "project";
			readonly moduleId?: string;
		}>;
	}>;
	readonly registries?: ReadonlyArray<string>;
	readonly registryDescriptors?: ReadonlyArray<{
		readonly apiVersion: number;
		readonly id: string;
		readonly source: "npm";
		readonly units: ReadonlyArray<{
			readonly addon: string;
			readonly framework: string;
			readonly kind: "adapter";
		}>;
		readonly version: string;
	}>;
}

function registryDescriptor(version: string) {
	return {
		apiVersion: 1,
		id: registryId,
		source: "npm",
		units: [{ addon: "vitest", framework: "nextjs", kind: "adapter" }],
		version,
	};
}

describe.runIf(process.env.FORGE_SMOKE === "1")("registry smoke", () => {
	it("installs the example registry through the packed CLI, applies its output and reports its update", async () => {
		await withScenarioWorkspace("smoke-registry", async (workspace) => {
			const cliPath = await installPackedForge(
				await packPackage("cli", workspace.workspaceRoot),
				workspace.workspaceRoot,
			);

			await createProject(
				workspace,
				{
					addons: ["vitest"],
					packageManager: "pnpm",
					web: "nextjs",
				},
				{ cliPath, install: true },
			);

			const originalManifest = await readJson<RegistryManifest>(
				join(workspace.projectRoot, ".forge/manifest.json"),
			);

			const registryRoot = join(workspace.workspaceRoot, "registry-package");
			await cp(join(repoRoot, "examples/registry-package"), registryRoot, {
				recursive: true,
			});

			const registryPackage = await readJson<RegistryPackageJson>(
				join(registryRoot, "package.json"),
			);

			expect(registryPackage.name).toBe(registryId);
			expect(registryPackage.version).toBe("0.1.0");
			expect(registryPackage.dependencies.effect).toBe(effectVersion);

			// A file dependency stands in for npm, since package-name resolution
			// needs a real registry before Forge can run the driven install.
			const installRegistry = async () => {
				const install = await runCommand(
					"pnpm",
					["add", "-D", "-w", `file:${registryRoot}`],
					{
						cwd: workspace.projectRoot,
						env: forgeEnvironment(workspace.workspaceRoot),
					},
				);

				expect(install.exitCode, `${install.stdout}\n${install.stderr}`).toBe(
					0,
				);
			};

			await installRegistry();

			const result = await runForge(
				workspace.projectRoot,
				["add", registryId],
				{
					cliPath,
					workspaceRoot: workspace.workspaceRoot,
				},
			);

			expect(result.stdout).toContain("Vitest now supports Next.js.");
			await expect(
				readFile(
					join(workspace.projectRoot, "apps/web/registry-adapter.txt"),
					"utf-8",
				),
			).resolves.toBe("Generated by the example registry.\n");

			const manifest = await readJson<RegistryManifest>(
				join(workspace.projectRoot, ".forge/manifest.json"),
			);

			expect(manifest.registries).toEqual([registryId]);
			expect(manifest.registryDescriptors).toEqual([
				registryDescriptor("0.1.0"),
			]);

			expect(
				manifest.installs.find((entry) => entry.definitionId === "vitest")
					?.targets,
			).toEqual([{ kind: "module", moduleId: expect.any(String) }]);

			await writeJson(join(registryRoot, "package.json"), {
				...registryPackage,
				version: "0.2.0",
			});

			await installRegistry();

			const update = await runForge(workspace.projectRoot, ["update"], {
				cliPath,
				workspaceRoot: workspace.workspaceRoot,
			});

			expect(update.stdout).toContain(`${registryId} 0.1.0 -> 0.2.0.`);
			await expect(
				readJson<RegistryManifest>(
					join(workspace.projectRoot, ".forge/manifest.json"),
				),
			).resolves.toMatchObject({
				registryDescriptors: [registryDescriptor("0.2.0")],
			});

			await runForge(workspace.projectRoot, ["remove", registryId], {
				cliPath,
				input: "y\r",
				workspaceRoot: workspace.workspaceRoot,
			});

			await expect(
				readJson<RegistryManifest>(
					join(workspace.projectRoot, ".forge/manifest.json"),
				),
			).resolves.toStrictEqual(originalManifest);

			expect(
				await pathExists(
					join(workspace.projectRoot, "apps/web/registry-adapter.txt"),
				),
			).toBe(false);
		});
	}, 600_000);
});
