import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	createProject,
	forgeEnvironment,
	pathExists,
	readJson,
	runCommand,
	runForge,
	withScenarioWorkspace,
	writeJson,
} from "../utils/harness";

interface RegistryManifest {
	readonly installs: ReadonlyArray<{
		readonly definitionId: string;
		readonly targets: ReadonlyArray<{
			readonly kind: "module" | "project";
			readonly moduleId?: string;
		}>;
	}>;
	readonly registries?: ReadonlyArray<string>;
	readonly registryDescriptors?: ReadonlyArray<{
		readonly apiVersion: number;
		readonly id: string;
		readonly source: "npm";
		readonly units: ReadonlyArray<{
			readonly addon: string;
			readonly framework: string;
			readonly kind: "adapter";
		}>;
		readonly version: string;
	}>;
}

describe.runIf(process.env.FORGE_SMOKE === "1")("registry smoke", () => {
	it("installs an adapter registry and applies its newly supported output", async () => {
		await withScenarioWorkspace("smoke-registry", async (workspace) => {
			await createProject(
				workspace,
				{
					addons: ["vitest"],
					packageManager: "pnpm",
					web: "nextjs",
				},
				{ install: true },
			);
			const originalManifest = await readJson<RegistryManifest>(
				join(workspace.projectRoot, ".forge/manifest.json"),
			);

			const registryRoot = join(
				workspace.projectRoot,
				"packages/fixture-registry",
			);
			await mkdir(registryRoot, { recursive: true });
			await writeJson(join(registryRoot, "package.json"), {
				exports: { ".": "./index.mjs" },
				name: "@fixture/forge-registry",
				type: "module",
				version: "1.2.3",
			});
			await writeFile(
				join(registryRoot, "index.mjs"),
				`const adapter = {
	_tag: "AdapterDefinition",
	addon: "vitest",
	framework: "nextjs",
	requiredSlots: [],
	contribute: ({ module }) => [{
		_tag: "LeafTextFileContribution",
		target: {
			_tag: "ResolvedModuleTarget",
			moduleId: module.id,
			moduleRoot: module.root,
		},
		path: "registry-adapter.txt",
		content: "Generated by the fixture registry.\\n",
	}],
};

export default {
	apiVersion: 1,
	adapters: [adapter],
	catalog: [],
};
`,
				"utf-8",
			);
			// The fixture uses a file dependency because package-name resolution still
			// requires a real npm registry before Forge can run the driven install.
			const install = await runCommand(
				"pnpm",
				["add", "-D", "-w", "file:packages/fixture-registry"],
				{
					cwd: workspace.projectRoot,
					env: forgeEnvironment(workspace.workspaceRoot),
				},
			);
			expect(install.exitCode, `${install.stdout}\n${install.stderr}`).toBe(0);

			const result = await runForge(
				workspace.projectRoot,
				["add", "@fixture/forge-registry"],
				{ workspaceRoot: workspace.workspaceRoot },
			);

			expect(result.stdout).toContain("Vitest now supports Next.js.");
			expect(
				await pathExists(
					join(workspace.projectRoot, "apps/web/registry-adapter.txt"),
				),
			).toBe(true);
			await expect(
				readFile(
					join(workspace.projectRoot, "apps/web/registry-adapter.txt"),
					"utf-8",
				),
			).resolves.toBe("Generated by the fixture registry.\n");

			const manifest = await readJson<RegistryManifest>(
				join(workspace.projectRoot, ".forge/manifest.json"),
			);
			expect(manifest.registries).toEqual(["@fixture/forge-registry"]);
			expect(manifest.registryDescriptors).toEqual([
				{
					apiVersion: 1,
					id: "@fixture/forge-registry",
					source: "npm",
					units: [
						{
							addon: "vitest",
							framework: "nextjs",
							kind: "adapter",
						},
					],
					version: "1.2.3",
				},
			]);
			expect(
				manifest.installs.find((entry) => entry.definitionId === "vitest")
					?.targets,
			).toEqual([{ kind: "module", moduleId: expect.any(String) }]);

			await runForge(
				workspace.projectRoot,
				["remove", "@fixture/forge-registry"],
				{ input: "y\r", workspaceRoot: workspace.workspaceRoot },
			);

			await expect(
				readJson<RegistryManifest>(
					join(workspace.projectRoot, ".forge/manifest.json"),
				),
			).resolves.toStrictEqual(originalManifest);
			expect(
				await pathExists(
					join(workspace.projectRoot, "apps/web/registry-adapter.txt"),
				),
			).toBe(false);
		});
	}, 600_000);
});
