name: "Setup & Install"
description: "Setup & Install"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Install Turbo
      shell: bash
      run: pnpm install -g turbo

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
