name: "Setup & Install"
description: "Setup & Install"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v7
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - uses: oven-sh/setup-bun@v2

    - name: Setup Yarn
      shell: bash
      run: |
        corepack enable
        corepack install -g yarn@stable

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
