import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { cn } from "@__SLUG__/ui/lib/utils";
import "@__SLUG__/ui/globals.css";

const geistSans = Geist({ variable: "--font-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-mono", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "__PROJECT_NAME__",
	description: "Generated by Forge",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen font-mono antialiased",
					geistSans.variable,
					geistMono.variable,
				)}
			>
				{children}
			</body>
		</html>
	);
}
