packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  # ===== BUILD TOOLS =====
  build:
    tsdown: ^0.12.8

  # ===== DEVELOPMENT TOOLS =====
  dev:
    # Git Hooks & Development Workflow
    lefthook: ^1.11.14
    
    # TypeScript & Compilation
    typescript: 5.8.3

  # ===== LINTING & FORMATTING =====
  lint:
    # Biome (ESLint/Prettier Alternative)
    "@biomejs/biome": 2.0.5
    
    # Commit Linting
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@commitlint/types": ^19.8.1

  # ===== MONOREPO =====
  monorepo:
    turbo: ^2.5.4

  # ===== NODE.JS ENVIRONMENT =====
  node:
    # CLI Framework
    "@clack/prompts": 1.0.0-alpha.1
    "@clack/core": 1.0.0-alpha.1

    # Color Utilities
    picocolors: ^1.1.1

  # ===== UTILITIES =====
  utils:
    # Validation
    zod: ^3.25.67

onlyBuiltDependencies:
  - lefthook
