packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  # ===== BUILD TOOLS =====
  build:
    tsdown: ^0.20.1

  # ===== DEVELOPMENT TOOLS =====
  dev:
    # Git Hooks & Development Workflow
    lefthook: ^2.0.16
    
    # TypeScript & Compilation
    typescript: 5.9.3

  # ===== LINTING & FORMATTING =====
  lint:
    # Biome (ESLint/Prettier Alternative)
    "@biomejs/biome": 2.3.13
    
    # Commit Linting
    "@commitlint/cli": ^20.4.2
    "@commitlint/config-conventional": ^20.4.2
    "@commitlint/types": ^20.4.0

  # ===== MONOREPO =====
  monorepo:
    turbo: ^2.8.11

  # ===== NODE.JS ENVIRONMENT =====
  node:
    # CLI Framework
    "@clack/prompts": 1.0.0
    "@clack/core": 1.0.0-alpha.7

    # Color Utilities
    picocolors: ^1.1.1

  # ===== UTILITIES =====
  utils:
    # Validation
    zod: ^4.3.6

onlyBuiltDependencies:
  - lefthook
