packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  # ===== BUILD TOOLS =====
  build:
    tsdown: ^0.15.9

  # ===== DEVELOPMENT TOOLS =====
  dev:
    # Git Hooks & Development Workflow
    lefthook: ^1.13.6
    
    # TypeScript & Compilation
    typescript: 5.9.3

  # ===== LINTING & FORMATTING =====
  lint:
    # Biome (ESLint/Prettier Alternative)
    "@biomejs/biome": 2.2.6
    
    # Commit Linting
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@commitlint/types": ^19.8.1

  # ===== MONOREPO =====
  monorepo:
    turbo: ^2.5.8

  # ===== NODE.JS ENVIRONMENT =====
  node:
    # CLI Framework
    "@clack/prompts": 1.0.0-alpha.6
    "@clack/core": 1.0.0-alpha.6

    # Color Utilities
    picocolors: ^1.1.1

  # ===== UTILITIES =====
  utils:
    # Validation
    zod: ^4.1.12

onlyBuiltDependencies:
  - lefthook
