import { Effect } from "effect";

const adapter = {
	_tag: "AdapterDefinition",
	addon: "vitest",
	framework: "nextjs",
	requiredSlots: [],
	contribute: ({ module }) =>
		Effect.succeed([
			{
				_tag: "LeafTextFileContribution",
				target: {
					_tag: "ResolvedModuleTarget",
					moduleId: module.id,
					moduleRoot: module.root,
				},
				path: "registry-adapter.txt",
				content: "Generated by the example registry.\n",
			},
		]),
};

export default {
	apiVersion: 1,
	adapters: [adapter],
	catalog: [],
};
