import "@__SLUG__/ui/globals.css";

import { cn } from "@__SLUG__/ui/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Providers } from "./providers";

const geistSans = Geist({ subsets: ["latin"], variable: "--font-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
  title: "__PROJECT_NAME__",
  description: "Generated by Forge",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        geistMono.variable,
        geistSans.variable,
        "bg-background font-sans text-foreground antialiased",
      )}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
