import { type Contribution, ensuredModuleTarget } from "@ryuujs/core";
import { Effect } from "effect";
import { describe, expect, it } from "vitest";
import type { ForgeConfig } from "../src";
import { loadDefinitionRegistry } from "../src";
import { tanstackStartFramework } from "../src/frameworks/tanstack-start";
import { versions } from "../src/versions";

const template = (() => {
	const found = loadDefinitionRegistry().registry.templates.find(
		(entry) => entry.id === "tanstack-start/base",
	);
	if (!found) throw new Error("Template Not Found: tanstack-start/base");
	return found;
})();

function contributionsFor(config: ForgeConfig): ReadonlyArray<Contribution> {
	const result = template.contribute({
		config,
		frameworks: [tanstackStartFramework],
	});
	if (result instanceof Promise || Effect.isEffect(result))
		throw new Error("Synchronous Contributions Expected: tanstack-start/base");

	return result;
}

function byTag<Tag extends Contribution["_tag"]>(tag: Tag) {
	return (
		contribution: Contribution,
	): contribution is Extract<Contribution, { _tag: Tag }> =>
		contribution._tag === tag;
}

function must<T>(value: T | undefined, label: string): T {
	if (value === undefined) throw new Error(`Missing Contribution: ${label}`);
	return value;
}

function textSurface(
	contributions: ReadonlyArray<Contribution>,
	surface: string,
) {
	return must(
		contributions
			.filter(byTag("ManagedTextSurfaceContribution"))
			.find((entry) => entry.surface === surface),
		surface,
	);
}

function jsonSurface(
	contributions: ReadonlyArray<Contribution>,
	surface: string,
) {
	return must(
		contributions
			.filter(byTag("ManagedJsonSurfaceContribution"))
			.find((entry) => entry.surface === surface),
		surface,
	);
}

function leafFile(contributions: ReadonlyArray<Contribution>, path: string) {
	return must(
		contributions
			.filter(byTag("LeafTextFileContribution"))
			.find((entry) => entry.path === path),
		path,
	);
}

describe("tanstack-start/base template", () => {
	it("activates only for the tanstack-start web framework", () => {
		expect(template.when({ web: "tanstack-start" })).toBe(true);
		expect(template.when({ web: "nextjs" })).toBe(false);
		expect(template.when({})).toBe(false);
	});

	it("declares the verified framework contract and slot map", () => {
		expect(tanstackStartFramework).toMatchObject({
			buildOutputs: ["dist/**"],
			configFile: "vite.config.ts",
			ignoreDirs: [".tanstack/"],
			slots: ["layout", "page", "api", "trpc", "auth"],
		});

		const contributions = contributionsFor({
			name: "Acme App",
			slug: "acme",
			web: "tanstack-start",
		});
		const ensure = must(
			contributions.find(byTag("EnsureModuleContribution")),
			"web module",
		);

		expect(ensure.moduleKey).toBe("web");
		expect(ensure.root).toBe("apps/web");
		expect(ensure.module.slots).toEqual({
			layout: "src/routes/__root.tsx",
			page: "src/routes/index.tsx",
			api: "src/routes/api",
			trpc: "src/routes/api/trpc/$.ts",
			auth: "src/routes/api/auth/$.ts",
		});
	});

	it("renders the Vite config, routes, env, router, and route tree", () => {
		const contributions = contributionsFor({
			name: "Acme App",
			slug: "acme",
			web: "tanstack-start",
		});

		expect(textSurface(contributions, "layout").content).toContain(
			'import appCss from "@acme/ui/globals.css?url";',
		);
		expect(textSurface(contributions, "layout").content).toContain(
			'{ title: "Acme App" }',
		);
		expect(textSurface(contributions, "page").content).toContain(
			">Acme App</h1>",
		);
		expect(leafFile(contributions, "env.ts").content).toContain(
			'clientPrefix: "VITE_"',
		);
		expect(leafFile(contributions, "src/router.tsx").content).toContain(
			"createTanStackRouter",
		);
		expect(leafFile(contributions, "src/routeTree.gen.ts").content).toContain(
			"automatically generated by TanStack Router",
		);
	});

	it("renders exact Vite configs with Tailwind cleanly switched on and off", () => {
		const withoutTailwind = textSurface(
			contributionsFor({ slug: "acme", web: "tanstack-start" }),
			"frameworkConfig",
		);
		expect(withoutTailwind.content).toBe(`import "./env";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";

const config = defineConfig({
  resolve: { tsconfigPaths: true },
  plugins: [tanstackStart(), viteReact()],
});

export default config;
`);

		const withTailwind = textSurface(
			contributionsFor({
				slug: "acme",
				style: "tailwind",
				web: "tanstack-start",
			}),
			"frameworkConfig",
		);
		expect(withTailwind.content).toBe(`import "./env";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import tailwindcss from "@tailwindcss/vite";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";

const config = defineConfig({
  resolve: { tsconfigPaths: true },
  plugins: [tailwindcss(), tanstackStart(), viteReact()],
});

export default config;
`);
	});

	it("mounts the tRPC provider only when tRPC is selected", () => {
		const bare = leafFile(
			contributionsFor({ slug: "acme", web: "tanstack-start" }),
			"src/providers.tsx",
		);
		expect(bare.target).toEqual(ensuredModuleTarget("web"));
		expect(bare.content).toContain("default: Fragment,");
		expect(bare.content).not.toContain("trpc:");
		expect(bare.content).not.toContain("TRPCReactProvider");

		const withTrpc = leafFile(
			contributionsFor({
				rpc: "trpc",
				slug: "acme",
				web: "tanstack-start",
			}),
			"src/providers.tsx",
		);
		expect(withTrpc.content).toContain(
			'import { TRPCReactProvider } from "@/trpc/react";',
		);
		expect(withTrpc.content).toContain("trpc: TRPCReactProvider,");
		expect(withTrpc.content).not.toMatch(/__[A-Z_]+__/);
	});

	it("uses the verified package versions and scripts", () => {
		const contributions = contributionsFor({
			slug: "acme",
			web: "tanstack-start",
		});
		const dependencySurface = must(
			contributions.find(byTag("ManagedDependenciesSurfaceContribution")),
			"packageJson dependencies",
		);
		const dependencyVersions = new Map(
			dependencySurface.dependencies.map((entry) => [
				entry.name,
				entry.version,
			]),
		);

		expect(dependencyVersions.get("@tanstack/react-start")).toBe(
			versions.tanstackReactStart.version,
		);
		expect(dependencyVersions.get("@tanstack/react-router")).toBe(
			versions.tanstackReactRouter.version,
		);
		expect(dependencyVersions.get("@tanstack/router-cli")).toBe(
			versions.tanstackRouterCli.version,
		);
		expect(dependencyVersions.get("vite")).toBe(versions.vite.version);
		expect(dependencyVersions.get("@vitejs/plugin-react")).toBe(
			versions.viteReact.version,
		);

		const scripts = must(
			contributions.find(byTag("ManagedScriptsSurfaceContribution")),
			"packageJson scripts",
		);
		expect(scripts.scripts).toEqual({
			build: "pnpm with-env vite build",
			dev: "pnpm with-env vite dev --port 3000",
			"generate-routes": "tsr generate",
			postinstall: "pnpm generate-routes",
			pretypecheck: "pnpm generate-routes",
			preview: "pnpm with-env vite preview",
			typecheck: "tsc --noEmit",
			"with-env": "dotenv -e ../../.env --",
		});

		expect(jsonSurface(contributions, "tsconfig").value).toMatchObject({
			extends: "@acme/tsconfig/tanstack-start.json",
			compilerOptions: {
				paths: {
					"@/*": ["./src/*"],
					"@acme/ui/*": ["../../packages/ui/src/*"],
				},
			},
		});
	});
});
