name: Snyk

on:
  pull_request:
    branches: ["*"]

  push:
    branches: ["main"]

  merge_group:

permissions:
  contents: read

jobs:
  snyk:
    name: Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    environment: Code Scanning
    env:
      SNYK_ORG: ${{ secrets.SNYK_ORG }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@28606799782bc8e809f4076e9f8293bc4212d05e

      - name: Setup
        uses: ./tooling/github/setup

      - name: Set Snyk Organization
        run: snyk config set org=$SNYK_ORG

      - name: Run Code Scan
        run: snyk code test --all-projects --sarif > snyk.sarif

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
